---
- name: LAMP Stack Installation
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Install PHP and required modules
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - php
        - libapache2-mod-php
        - php-mysql

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes